### ISSUE TITLE
Unbreak Homebrew

### ISSUE THREAD

**Issue by nikolay** [gwerbin/homebrew-tap#7]
```
$ brew search ...
Error: Calling Hbc::DSL#license is disabled!
There is no replacement.
/usr/local/Homebrew/Library/Taps/gwerbin/homebrew-tap/Casks/sqleo.rb:8:in `block in load'
Please report this to the gwerbin/tap tap!
Or, even better, submit a PR to fix it!
```

**Comment by gwerbin** [comment]
I have not updated this in six months. Unfortunately the Mac I was using for development  is in some kind of tenuous half-dead state.  Due to recent personal difficulties I have not had the time to deal with it. Please do not use this repo. I have updated the description.

I encourage you to fork if you need one of the formulas in here.  I never intended this to become a production repo for any projects, so if you are relying on this I strongly recommend that you contact maintainer of the package and ask them to host their own Tap or submit to Homebrew core.

**Comment by nikolay** [comment]
I'm sorry to hear that, @gwerbin! Thanks for your work!
